//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreGeneral.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreGeneral.Recursos.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string EtiquetaActivo {
            get {
                return ResourceManager.GetString("EtiquetaActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador.
        /// </summary>
        public static string EtiquetaAdmin {
            get {
                return ResourceManager.GetString("EtiquetaAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string EtiquetaApellido {
            get {
                return ResourceManager.GetString("EtiquetaApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido 1.
        /// </summary>
        public static string EtiquetaApellido1 {
            get {
                return ResourceManager.GetString("EtiquetaApellido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido 2.
        /// </summary>
        public static string EtiquetaApellido2 {
            get {
                return ResourceManager.GetString("EtiquetaApellido2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celular.
        /// </summary>
        public static string EtiquetaCelular {
            get {
                return ResourceManager.GetString("EtiquetaCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string EtiquetaCiudadNombre {
            get {
                return ResourceManager.GetString("EtiquetaCiudadNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave.
        /// </summary>
        public static string EtiquetaClave {
            get {
                return ResourceManager.GetString("EtiquetaClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string EtiquetaClienteNombre {
            get {
                return ResourceManager.GetString("EtiquetaClienteNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string EtiquetaCodigo {
            get {
                return ResourceManager.GetString("EtiquetaCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consecutivo.
        /// </summary>
        public static string EtiquetaConsecutivo {
            get {
                return ResourceManager.GetString("EtiquetaConsecutivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string EtiquetaCorreo {
            get {
                return ResourceManager.GetString("EtiquetaCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string EtiquetaDescripcion {
            get {
                return ResourceManager.GetString("EtiquetaDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string EtiquetaDireccion {
            get {
                return ResourceManager.GetString("EtiquetaDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es Sistema.
        /// </summary>
        public static string EtiquetaEsSistema {
            get {
                return ResourceManager.GetString("EtiquetaEsSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string EtiquetaEstado {
            get {
                return ResourceManager.GetString("EtiquetaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string EtiquetaFecha {
            get {
                return ResourceManager.GetString("EtiquetaFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma Contacto.
        /// </summary>
        public static string EtiquetaFormaContacto {
            get {
                return ResourceManager.GetString("EtiquetaFormaContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string EtiquetaId {
            get {
                return ResourceManager.GetString("EtiquetaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Agente.
        /// </summary>
        public static string EtiquetaIdAgente {
            get {
                return ResourceManager.GetString("EtiquetaIdAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente.
        /// </summary>
        public static string EtiquetaidAgenteNombre {
            get {
                return ResourceManager.GetString("EtiquetaidAgenteNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación.
        /// </summary>
        public static string EtiquetaIdentificacion {
            get {
                return ResourceManager.GetString("EtiquetaIdentificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación Responsable.
        /// </summary>
        public static string EtiquetaIdentificacionResponsable {
            get {
                return ResourceManager.GetString("EtiquetaIdentificacionResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        public static string EtiquetaidRol {
            get {
                return ResourceManager.GetString("EtiquetaidRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciales.
        /// </summary>
        public static string EtiquetaIniciales {
            get {
                return ResourceManager.GetString("EtiquetaIniciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string EtiquetaNombre {
            get {
                return ResourceManager.GetString("EtiquetaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre 1.
        /// </summary>
        public static string EtiquetaNombre1 {
            get {
                return ResourceManager.GetString("EtiquetaNombre1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre 2.
        /// </summary>
        public static string EtiquetaNombre2 {
            get {
                return ResourceManager.GetString("EtiquetaNombre2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Responsable.
        /// </summary>
        public static string EtiquetaNombreResponsable {
            get {
                return ResourceManager.GetString("EtiquetaNombreResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observación.
        /// </summary>
        public static string EtiquetaObservacion {
            get {
                return ResourceManager.GetString("EtiquetaObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación.
        /// </summary>
        public static string EtiquetaOperacion {
            get {
                return ResourceManager.GetString("EtiquetaOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Placa.
        /// </summary>
        public static string EtiquetaPlaca {
            get {
                return ResourceManager.GetString("EtiquetaPlaca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string EtiquetaTelefono {
            get {
                return ResourceManager.GetString("EtiquetaTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tel. Responsable.
        /// </summary>
        public static string EtiquetaTelResponsable {
            get {
                return ResourceManager.GetString("EtiquetaTelResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string EtiquetaTipo {
            get {
                return ResourceManager.GetString("EtiquetaTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string EtiquetaUsuario {
            get {
                return ResourceManager.GetString("EtiquetaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string EtiquetaValor {
            get {
                return ResourceManager.GetString("EtiquetaValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo Requerido.
        /// </summary>
        public static string MensajeRequerido {
            get {
                return ResourceManager.GetString("MensajeRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo no puede tener más de {0} caracteres..
        /// </summary>
        public static string MensajeTamanoMaximo {
            get {
                return ResourceManager.GetString("MensajeTamanoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agentes.
        /// </summary>
        public static string TituloAgenteListar {
            get {
                return ResourceManager.GetString("TituloAgenteListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Agente.
        /// </summary>
        public static string TituloBloqueAgenteConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueAgenteConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Agente.
        /// </summary>
        public static string TituloBloqueAgenteInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueAgenteInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Agente.
        /// </summary>
        public static string TituloBloqueAgenteModificar {
            get {
                return ResourceManager.GetString("TituloBloqueAgenteModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Ciudad.
        /// </summary>
        public static string TituloBloqueCiudadConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueCiudadConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Ciudad.
        /// </summary>
        public static string TituloBloqueCiudadInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueCiudadInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Ciudad.
        /// </summary>
        public static string TituloBloqueCiudadModificar {
            get {
                return ResourceManager.GetString("TituloBloqueCiudadModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Cliente.
        /// </summary>
        public static string TituloBloqueClienteConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueClienteConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Cliente.
        /// </summary>
        public static string TituloBloqueClienteInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueClienteInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Cliente.
        /// </summary>
        public static string TituloBloqueClienteModificar {
            get {
                return ResourceManager.GetString("TituloBloqueClienteModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Conductor.
        /// </summary>
        public static string TituloBloqueConductorConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueConductorConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Conductor.
        /// </summary>
        public static string TituloBloqueConductorInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueConductorInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Conductor.
        /// </summary>
        public static string TituloBloqueConductorModificar {
            get {
                return ResourceManager.GetString("TituloBloqueConductorModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Grupo de Elementos.
        /// </summary>
        public static string TituloBloqueGrupoElementoConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueGrupoElementoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Grupo de Elementos.
        /// </summary>
        public static string TituloBloqueGrupoElementoInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueGrupoElementoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Grupo de Elementos.
        /// </summary>
        public static string TituloBloqueGrupoElementoModificar {
            get {
                return ResourceManager.GetString("TituloBloqueGrupoElementoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Lista Precios.
        /// </summary>
        public static string TituloBloqueListaPrecioConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueListaPrecioConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insetar Lista Precios.
        /// </summary>
        public static string TituloBloqueListaPrecioInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueListaPrecioInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Lista Precios.
        /// </summary>
        public static string TituloBloqueListaPrecioModificar {
            get {
                return ResourceManager.GetString("TituloBloqueListaPrecioModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Parametro.
        /// </summary>
        public static string TituloBloqueParametroConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueParametroConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insetar Parrametro.
        /// </summary>
        public static string TituloBloqueParametroInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueParametroInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Parametro.
        /// </summary>
        public static string TituloBloqueParametroModificar {
            get {
                return ResourceManager.GetString("TituloBloqueParametroModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Proveedor.
        /// </summary>
        public static string TituloBloqueProveedorConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueProveedorConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Proveedor.
        /// </summary>
        public static string TituloBloqueProveedorInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueProveedorInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Proveedor.
        /// </summary>
        public static string TituloBloqueProveedorModificar {
            get {
                return ResourceManager.GetString("TituloBloqueProveedorModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Cliente.
        /// </summary>
        public static string TituloBloqueProyectoConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueProyectoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Cliente.
        /// </summary>
        public static string TituloBloqueProyectoInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueProyectoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Cliente.
        /// </summary>
        public static string TituloBloqueProyectoModificar {
            get {
                return ResourceManager.GetString("TituloBloqueProyectoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Tipo Documento.
        /// </summary>
        public static string TituloBloqueTipoDocumentoConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueTipoDocumentoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Tipo Documento.
        /// </summary>
        public static string TituloBloqueTipoDocumentoInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueTipoDocumentoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Tipo Documento.
        /// </summary>
        public static string TituloBloqueTipoDocumentoModificar {
            get {
                return ResourceManager.GetString("TituloBloqueTipoDocumentoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Tipo Mantenimiento.
        /// </summary>
        public static string TituloBloqueTipoMantenimientoConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueTipoMantenimientoConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Tipo Mantenimiento.
        /// </summary>
        public static string TituloBloqueTipoMantenimientoInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueTipoMantenimientoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Tipo Mantenimiento.
        /// </summary>
        public static string TituloBloqueTipoMantenimientoModificar {
            get {
                return ResourceManager.GetString("TituloBloqueTipoMantenimientoModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Unidad Medida.
        /// </summary>
        public static string TituloBloqueUnidadMedidaConsultar {
            get {
                return ResourceManager.GetString("TituloBloqueUnidadMedidaConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Unidad Medida.
        /// </summary>
        public static string TituloBloqueUnidadMedidaInsertar {
            get {
                return ResourceManager.GetString("TituloBloqueUnidadMedidaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Unidad Medida.
        /// </summary>
        public static string TituloBloqueUnidadMedidaModificar {
            get {
                return ResourceManager.GetString("TituloBloqueUnidadMedidaModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudades.
        /// </summary>
        public static string TituloCiudadListar {
            get {
                return ResourceManager.GetString("TituloCiudadListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string TituloClienteListar {
            get {
                return ResourceManager.GetString("TituloClienteListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conductores.
        /// </summary>
        public static string TituloConductorListar {
            get {
                return ResourceManager.GetString("TituloConductorListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos de Elementos.
        /// </summary>
        public static string TituloGrupoElementoListar {
            get {
                return ResourceManager.GetString("TituloGrupoElementoListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listas de Precios.
        /// </summary>
        public static string TituloListaPrecioListar {
            get {
                return ResourceManager.GetString("TituloListaPrecioListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parametros.
        /// </summary>
        public static string TituloParametroListar {
            get {
                return ResourceManager.GetString("TituloParametroListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores.
        /// </summary>
        public static string TituloProveedorListar {
            get {
                return ResourceManager.GetString("TituloProveedorListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string TituloProyectoListar {
            get {
                return ResourceManager.GetString("TituloProyectoListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos Documentos.
        /// </summary>
        public static string TituloTipoDocumentoListar {
            get {
                return ResourceManager.GetString("TituloTipoDocumentoListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos Mantenimientos.
        /// </summary>
        public static string TituloTipoMantenimientoListar {
            get {
                return ResourceManager.GetString("TituloTipoMantenimientoListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades de Medida.
        /// </summary>
        public static string TituloUnidadMedidaListar {
            get {
                return ResourceManager.GetString("TituloUnidadMedidaListar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Login.
        /// </summary>
        public static string TituloUsuarioLogin {
            get {
                return ResourceManager.GetString("TituloUsuarioLogin", resourceCulture);
            }
        }
    }
}
